name: Protect main branch
branches:
  - pattern: main
    protection: # GitHub Actions and Protection Rules do not care about the sequence — only about the presence and exact naming match.
      required_status_checks:
        strict: true # the source must be up to date with this target main before PR "so must pull main on source"
        contexts:
          - "CI Pipeline / call-tests"
          - "CI Pipeline / call-lint" 
          - "CI Pipeline / call-trivy"
          - "CI Pipeline / call-sbom"
          - "CI Pipeline / call-codeql"
          - "CI Pipeline / call-scan"
        
      required_pull_request_reviews:
        required_approving_review_count: 1 
        dismiss_stale_reviews: true 
        require_code_owner_reviews: true 
        bypass_pull_request_allowances: 
          users:
            - WahbaMousa-DevOps
      enforce_admins: true  
      restrictions:
        users:
          - WahbaMousa-DevOps  
         # - github-actions[bot]
        teams: []
        apps: []
      allow_force_pushes: false 
      allow_deletions: false   

      require_linear_history: false
      required_conversation_resolution: true  

      lock_branch: false 
      block_recreations: false
