# GitHub Branch Protection Rules (via Settings > Branches)

# Main Branch Protection
---
name: main
protection_rules:
  # Require pull request reviews
  required_pull_request_reviews:
    required_approving_review_count: 2  # Professional: 2 approvals
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    restrict_dismissals: true
    dismissal_restrictions:
      users: ["WahbaMousa-DevOps"]
      teams: []

  # Required status checks (only CI, not deployment)
  required_status_checks:
    strict: true  # Require branches to be up-to-date
    contexts:
      # CI Pipeline checks only
      - "CI Pipeline"                    # From CI Pipeline

  # Additional protections
  enforce_admins: true            # Apply to admins too
  allow_force_pushes: false       # Critical for main
  allow_deletions: false          # Prevent accidental deletion
  require_linear_history: true    # Clean git history
  required_conversation_resolution: true
  
  # Push restrictions (optional)
  restrictions:
    users: ["WahbaMousa-DevOps"]  # Only you can push directly
    teams: []
    apps: []
---
# Release Branch Protection  
name: release
protection_rules:
  required_pull_request_reviews:
    required_approving_review_count: 1  # Less strict for staging
    dismiss_stale_reviews: true
    require_code_owner_reviews: false

  required_status_checks:
    strict: true
    contexts:
      - "CI Pipeline" 

  enforce_admins: false
  allow_force_pushes: false
  allow_deletions: false
  require_linear_history: true
  required_conversation_resolution: true
---