version: 2 #  Updates your project dependencies (libraries your code uses)
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"  #force PRs to go to develop
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"

  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "develop"  
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"
