title = "My Company Gitleaks Config"
[allowlist]
  paths = ["docs/", "README.md"]
  commits = []
  regexes = ["dummy_api_key"]

[[rules]]
description = "Generic API Key"
regex = '''(?i)apikey\s*[:=]\s*["']?[a-z0-9]{32,}["']?'''
tags = ["key", "API"]
