# ✅ secret.yml for GitHub Secret Scanning in .github.io
# (Note: This is for GitHub's native secret scanning configuration)

# This file is only valid if GitHub Advanced Security is enabled
# and resides in .github/secret-scanning.yml or .github/secret.yml

# Minimal example for notification and PR blocking
version: 2

# Block PRs that introduce secrets
# Only works on public repos or private repos with GHAS
on_push:
  report_secrets: true
  block_push: true

on_pull_request:
  report_secrets: true
  block_pull_request: true
