aliveStatusCodes:
  - 200
  - 406
  - 429
dirs:
  - .
  - .github
excludedDirs:
  - eng/readme-templates
ignorePatterns:
  - pattern: "^https://github.com/microsoft/mcr.*$"
  - pattern: "^https://github.com/dotnet/release.*$"
  - pattern: "^https://aka.ms/$"
useGitIgnore: true
