name: Accessibility Check

on:
  push:
    branches:
    - main
    - release
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run axe accessibility check
        uses: amir295/axe-core-action@v1
        with:
          url: ${{ env.ENV_BASE_URL }} 
