name: Accessibility Check

on:
  # push:
  #   branches:
  #   - main
  #   - release
  workflow_dispatch:

jobs:
  accessibility:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Start local server
      run: npm start &  # Run in background
    - name: Run axe check
      uses: amir295/axe-core-action@v1
      with:
        url: "http://localhost:3000"  # Use your app's local port