name: Auto Label Dependabot PRs

on:
  pull_request:
    types: [opened]

jobs:
  label:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Add automerge label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
          github_token: ${{ secrets.BOT_TOKEN }}
