# Build Pipeline (Reusable Workflow)
name: Build Pipeline

on:
  workflow_call:  # Makes this workflow callable from another workflow using 'uses:'
    inputs:
      environment:
        required: true
        type: string
jobs:
  build:
    name: Build GitHub Pages Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Required to access the repo content

      - name: Setup Pages
        uses: actions/configure-pages@v5  # Configures environment for GitHub Pages (used by Jekyll)

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./              # Source directory for Jekyll
          destination: ./_site    # Output directory (build result goes here)
        env:
          # Set base URL based on branch
          ENV_BASE_URL: ${{ 
            contains(github.ref, 'release') 
              ? 'https://staging.aiopsvision.com' 
              : 'https://wahba.aiopsvision.com' }}
              
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./_site


  # test:
  #   name: Run Unit Tests
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run Tests
  #       run: echo "Running unit tests"

  # lint:
  #   name: Lint Code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Lint Code
  #       run: echo "Linting code"

  # trivy:
  #   name: Scan with Trivy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Run Trivy Scanner
  #       uses: aquasecurity/trivy-action@master

  # sbom:
  #   name: Generate CycloneDX SBOM
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Generate SBOM
  #       run: echo "Generating SBOM"