name: Build Pipeline

on:
  workflow_call:
jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean Old Site Folder (if exists)
        run: rm -rf _site || true

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Artifact for Deploy Workflow
        uses: actions/upload-artifact@v4 # v4 as public use 
        with:
          name: jekyll-site    # MUST match deploy package name 
          path: ./_site