name: Build Pipeline

on:
  workflow_call:
    # inputs:
    #   environment:
    #     required: true
    #     type: string

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -rf _site || true
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./ # Source directory for Jekyll
          destination: ./_site # Output directory (build result goes here)
        # env:
        #   ENV_BASE_URL: ${{inputs.environment == 'staging'?'https://staging.aiopsvision.com':'https://wahba.aiopsvision.com'}}
      - uses: actions/upload-artifact@v4

        with:
          name: build-artifact-temp1
          path: ./_site
       
