name: Deploy to Dev

on:
  workflow_dispatch: {}  

  workflow_run:
    workflows: ["CI Pipeline"] # must exactly match the name in CI-ci.yml
    types:
      - completed
    branches:
      - develop

concurrency:
  group: "dev-deploy-${{ github.ref }}"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ env.ENV_BASE_URL }}

    # Only run if the CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Jekyll gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Debug Event Context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
        if: github.event_name == 'workflow_run'

      - name: Download Jekyll Artifact
        uses: actions/download-artifact@v4
        with:
          name: jekyll-site
          path: ./_site
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
      
      - name: Verify deployment
        run: echo "Deployed to:${{ steps.deployment.outputs.page_url }}"