name: Swap Staging to Production

on:
  workflow_dispatch:
    inputs:
      swap_direction:
        description: 'Enter "toblue" (promote green to blue) or "togreen" (promote blue to green)'
        required: true

jobs:
  swap:
    name: Swap Green ↔ Blue Environment
    if: github.event.inputs.swap_direction == 'toblue' || github.event.inputs.swap_direction == 'togreen'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout destination branch
        uses: actions/checkout@v4
        with:
          # Checkout the branch we're promoting TO (the destination)
          ref: ${{ github.event.inputs.swap_direction == 'toblue' && 'blue' || 'green' }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Perform swap merge
        run: |
          if [[ "${{ github.event.inputs.swap_direction }}" == "toblue" ]]; then
            # Promote green TO blue (green becomes production)
            echo "Promoting green branch to blue (production)"
            git fetch origin green:green
            git merge --no-ff green -m "Promote green to blue (production)"
            git push origin blue
          elif [[ "${{ github.event.inputs.swap_direction }}" == "togreen" ]]; then
            # Promote blue TO green (blue becomes production)  
            echo "Promoting blue branch to green (production)"
            git fetch origin blue:blue
            git merge --no-ff blue -m "Promote blue to green (production)"
            git push origin green
          fi

      - name: Trigger Production Deployment
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: deploy-prod