name: CI Pipeline 
#  Centralized CI Aggregator.

on:
  push:
    branches: [develop, release, main, 'feature/*', 'hotfix/*']  # Triggers for all branches including feature & hotfix

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml  # Reusable unit test job

  call-lint:
    uses: ./.github/workflows/lint.yml  # Code linting job

  call-trivy:
    uses: ./.github/workflows/trivy.yml  # Security scan job

  call-sbom:
    uses: ./.github/workflows/sbom.yml  # Software Bill of Materials generation

  call-codeql:
    uses: ./.github/workflows/codeql.yml  # Static analysis for vulnerabilities

  call-build:
    uses: ./.github/workflows/build.yml  # Runs the reusable build workflow
    with:
      environment: ${{ github.ref_name == 'release' ? 'staging' : 'production' }}

reupload-artifact:
  steps:
    - uses: actions/download-artifact@v4
    - uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: ./_site
        retention-days: 1  # Add retention