name: CI Pipeline 
#  Centralized CI Aggregator.

on:
  push:
    branches: [develop, release, main, 'feature/*', 'hotfix/*']  # Triggers for all branches including feature & hotfix

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml  # Reusable unit test job

  call-lint:
    uses: ./.github/workflows/lint.yml  # Code linting job

  call-trivy:
    uses: ./.github/workflows/trivy.yml  # Security scan job

  call-sbom:
    uses: ./.github/workflows/sbom.yml  # Software Bill of Materials generation

  call-codeql:
    uses: ./.github/workflows/codeql.yml  # Static analysis for vulnerabilities

  call-build:
    uses: ./.github/workflows/build.yml  # Runs the reusable build workflow

  reupload-artifact:
    name: Re-upload Artifact from Build Pipeline
    runs-on: ubuntu-latest
    needs: call-build  # Ensures this runs only after the build job finishes.

    steps:
      - name: Download artifact from reusable workflow
        uses: actions/download-artifact@v3
        with:
          name: build-output-temp      # Must match upload name from build.yml
          path: ./_site                    # Must match to keep paths consistent

      - name: Re-upload artifact for deploy workflow_run visibility
        uses: actions/upload-artifact@v4
        with:
          name: build-output      # Re-uploads with the same name for staging workflow
          path: ./_site
