name: CI Pipeline

on:
  push:
    branches: [develop, release, main, 'feature/*', 'hotfix/*']

# env:
#   ENVIRONMENT: ${{ contains('release develop', github.ref_name) && 'staging' || 'production' }}

jobs:
  call-tests:
    uses: ./.github/workflows/test.yml

  call-lint:
    uses: ./.github/workflows/lint.yml

  call-trivy:
    uses: ./.github/workflows/trivy.yml

  call-sbom:
    uses: ./.github/workflows/sbom.yml

  call-codeql:
    uses: ./.github/workflows/codeql.yml

  call-build:
    uses: ./.github/workflows/build.yml
    # with:
    #   environment: ${{ env.ENVIRONMENT }}

