name: Deploy to Production

on:
  workflow_run:
    workflows: ["Deploy to Staging"]
    types: [completed]
    branches: [main]

concurrency:
  group: "prod-deploy-${{ github.ref }}"
  cancel-in-progress: false

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://wahba.aiopsvision.com  # Fixed production URL

    steps:
      - name: Download staged artifact
        uses: actions/download-artifact@v4
        with:
          name: site-build  # Must match upload name in staging
          path: ./_site

      - name: Set Production CNAME
        run: echo "wahba.aiopsvision.com" > _site/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3  # Use v3

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
      
      - name: Show deployment URL
        run: echo "Deployed to:${{ steps.deployment.outputs.page_url }}"