name: Lint and Link Check

on:
  workflow_call:
  push:
    paths:
      - '**.md'
      - .markdownlint.yml
      - .linkspector.yml

jobs:
  md-link:
   name: 🔗 Link Checker-Markdown Lint
   runs-on: ubuntu-latest

   steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v3
      with:
        files: "."
        config_file: ".markdownlint.yml"


    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install linkspector
      run: npm install -g @umbrelladocs/action-linkspector

    - name: Run linkspector
      run: linkspector --config .linkspector.yml
